---
version: "3.8"

services:

  db:
    image: postgres:15
    env_file: ./postgres.env
    ports:
      - "5432:5432"
    networks:
      - net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - net

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
     - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS is the hostname:port that clients will connect to
      # PLAINTEXT removes authentication and encryption from the listener.
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - net


  code:
    build: .
    environment:
      - PYTHONUNBUFFERED=0
    networks:
      - net


networks:
  net:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.0.56.0/24
